#!/usr/bin/env python3
"""Generate concrete XCTest methods from the .feature files.

The .feature files in TellyUITests/Features/ are the source of truth. XCTest
needs real (selector-addressable) test methods for `-only-testing` filtering
and crash recovery, so we generate one thin `test…` per scenario, each
delegating to `runScenario(feature:scenario:)`. The generated file is checked in
and kept in sync by a quality gate (`--check`).

Usage:
  python3 scripts/generate_acceptance_tests.py          # write the generated file
  python3 scripts/generate_acceptance_tests.py --check  # fail if out of date
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FEATURES_DIR = REPO / "TellyUITests" / "Features"
OUTPUT = REPO / "TellyUITests" / "AcceptanceTests.generated.swift"

HEADER = """// @generated by scripts/generate_acceptance_tests.py — DO NOT EDIT.
// Source of truth: TellyUITests/Features/*.feature
// Regenerate with: python3 scripts/generate_acceptance_tests.py
import XCTest

extension AcceptanceTests {
"""
FOOTER = "}\n"


def parse_features():
    """Return [(feature_name, file_name, [scenario_name, ...]), ...]."""
    out = []
    if not FEATURES_DIR.exists():
        return out
    for path in sorted(FEATURES_DIR.glob("*.feature")):
        feature_name = None
        scenarios = []
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line.startswith("Feature:"):
                feature_name = line[len("Feature:"):].strip()
            elif line.startswith("Scenario:"):
                scenarios.append(line[len("Scenario:"):].strip())
        if feature_name:
            out.append((feature_name, path.name, scenarios))
    return out


def selector_fragment(name):
    """Non-alphanumerics become underscores, mirroring the runner's naming."""
    return re.sub(r"[^0-9A-Za-z]", "_", name)


def swift_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render():
    lines = [HEADER]
    for feature_name, file_name, scenarios in parse_features():
        lines.append(f"\n    // MARK: - {feature_name}\n")
        for scenario in scenarios:
            method = "test_" + selector_fragment(scenario)
            lines.append(f"    func {method}() throws {{")
            lines.append(
                f'        try runScenario(feature: "{swift_escape(file_name)}", '
                f'scenario: "{swift_escape(scenario)}")'
            )
            lines.append("    }\n")
    lines.append(FOOTER)
    return "\n".join(lines)


def main():
    content = render()
    check = "--check" in sys.argv
    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("✗ AcceptanceTests.generated.swift is out of date.")
            print("  Run: python3 scripts/generate_acceptance_tests.py")
            sys.exit(1)
        print("✓ Generated acceptance tests are in sync with .feature files.")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        n = sum(len(s) for _, _, s in parse_features())
        print(f"✓ Wrote {OUTPUT.relative_to(REPO)} ({n} scenarios).")


if __name__ == "__main__":
    main()
