// @generated by scripts/generate_acceptance_tests.py — DO NOT EDIT.
// Source of truth: TellyUITests/Features/*.feature
// Regenerate with: python3 scripts/generate_acceptance_tests.py
import XCTest

extension AcceptanceTests {


    // MARK: - App Launch

    func test_Shows_the_welcome_screen_on_first_launch() throws {
        try runScenario(feature: "onboarding.feature", scenario: "Shows the welcome screen on first launch")
    }

}
